### ISSUE TITLE
What sort of license are these under?

### ISSUE THREAD

**Issue by RangerMauve** [tfolbrecht/dwebdoodlin#1]
Hey! These are so cool!

I'd love to be able to use the Dat logo for some VR stuff I'm doing. What sort of license are you releasing these under? 😁

Also, mind if I share this repo in the Dat newsletter?

**Comment by tfolbrecht** [comment]
Ahh, Sorry for not checking!

I'd say they inherit the license of the logo they're based on.
Sorry this was just a quicky. Let me know what I have to do license-wise.

DM on Twitter and I'll send you some 😊
